name: calculatorProject
services:
  mariadb:
    image: mariadb:latest
    container_name: db
    restart: always
    privileged: true
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PWD}   
      MARIADB_DATABASE: ${MYSQL_DB}             
      MARIADB_USER: ${MYSQL_USER}               
      MARIADB_PASSWORD: ${MYSQL_PWD}
    volumes:
      - mariadb_data:/var/lib/mysql
    
  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    depends_on:
      - mariadb
    volumes:
      - ./db/migrations:/flyway/sql
    command: "migrate"
    environment:
      FLYWAY_URL: ${FLYWAY_URL}
      FLYWAY_USER: ${MYSQL_USER}
      FLYWAY_PASSWORD: ${MYSQL_PWD}
      FLYWAY_CONNECT_RETRIES: 10
      FLYWAY_CONNECT_RETRIES_INTERVAL: 5
  
  api:
    image: ghcr.io/${GH_REPO}-api:staging
    container_name: api
    restart: always
    depends_on:
      - flyway
    environment:
      DB_CON_STR: ${DB_CON_STR}
      LOG_LEVEL: ${LOG_LEVEL}
      ZIPKIN_URL: ${ZIPKIN_URL}
      SEQ_URL: ${SEQ_URL}
    ports:
      - "${API_PORT}:8080"
  
  react:
    image: ghcr.io/${GH_REPO}-react:staging
    container_name: react
    restart: always
    depends_on:
      - api
    ports:
      - "${REACT_PORT}:80"

volumes:
  mariadb_data: